# App name
spring.application.name=cms

# H2 database (temporary local DB for Sprint 1)
spring.datasource.url=jdbc:h2:mem:cmsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA (auto-create tables from Java classes)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 console (so you can SEE the database in browser)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
